# Docker Compose Configuration
# visit https://docs.docker.com/compose/

version: '3.8'

networks:
  dev:

services:

  # start the mongodb service as container
  database:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: 
      MONGO_INITDB_ROOT_PASSWORD: 
    networks:
      - dev


  # app service for your backend
  app:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_NAME: 
      DATABASE_USER: 
      DATABASE_PASS: 
      DATABASE_URI: mongodb://database:27017
    ports:
      - '3000:3000'
    depends_on:
      - database
    networks:
      - dev

