version: '3.3'
services:
  mongo:
    image: mongo
    volumes:
      - mongo-data:/data/db
    restart: always
    expose:
      - "27017"
  app:
    image: backend/nestjs
    expose:
      - "3000"
    links:
      - mongo
    depends_on:
      - mongo
    restart: "no"
    environment:
      MONGO_URL: mongo
volumes:
  mongo-data: {}
